//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JYMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Role
    {
        public string F_R_Bm { get; set; }
        public string F_R_Name { get; set; }
        public string F_D_Bm { get; set; }
        public string F_R_Description { get; set; }
        public string F_R_CreatedBy { get; set; }
        public Nullable<System.DateTime> F_R_CreatedTime { get; set; }
        public string F_R_ModifiedBy { get; set; }
        public Nullable<System.DateTime> F_R_ModifiedTime { get; set; }
    }
}
