//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JYMES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public string F_U_Bm { get; set; }
        public string F_U_Name { get; set; }
        public string F_U_Short { get; set; }
        public string F_D_Bm { get; set; }
        public Nullable<bool> F_U_Sex { get; set; }
        public Nullable<System.DateTime> F_U_Birthday { get; set; }
        public string F_U_Education { get; set; }
        public string F_U_Role { get; set; }
        public string F_U_Type { get; set; }
        public Nullable<System.DateTime> F_U_Intime { get; set; }
        public Nullable<System.DateTime> F_U_Outtime { get; set; }
        public Nullable<bool> F_U_Enabled { get; set; }
        public string F_U_Password { get; set; }
        public string F_U_CreatedBy { get; set; }
        public Nullable<System.DateTime> F_U_CreatedTime { get; set; }
        public string F_U_ModifiedBy { get; set; }
        public Nullable<System.DateTime> F_U_ModifiedTime { get; set; }
    }
}
